### ISSUE TITLE
Image quality inquiry

### ISSUE THREAD

**Issue by je-santos** [AlexandreAdam/score_models#10]
Thanks for this great library. Finally a nice, clean, and easy to run implementation of these models.
I was wondering, have you conducted any benchmarks (specifically FID) of Song's model?

Thanks a lot!!

**Comment by AlexandreAdam** [comment]
I have not conducted any benchmarking tests. I mainly apply these models for settings in astronomy, where there aren't any accepted benchmarks. But, since I mostly reuse the NCSN++ architecture from Yang Song's repository, you can refer to his [CIFAR-10 benchmark](https://paperswithcode.com/sota/image-generation-on-cifar-10) as a general idea of where the architecture stands compared to other setups. The entry from his 2021 paper has an FID of 2.20 (ranked 28 as of writing this comment).

**Comment by je-santos** [comment]
Great, thanks!!!!
